name: Main workflow

on:
  push:
    branches: 
      - foo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-14 # beta runner for macos arm64
          - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-compiler:
          - "5.1"
          - "4.14"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: |
            *.opam

      - run: opam depext owl-plplot --with-test
    
      - run: |
          opam install owl-plplot --yes --deps-only --with-test
          opam exec -- dune build -p owl-base
          opam exec -- dune runtest -p owl-base
  
